import type { Camp } from "./types";

/**
 * Seed dataset of real US camps, compiled from public sources.
 * All entries are `verified: false` — figures (tuition, size, dates) are
 * good-faith estimates until a camp claims and verifies its listing.
 * The scraper pipeline in /scripts/scraper is designed to grow this into
 * a national dataset stored in Supabase.
 */
export const SEED_CAMPS: Camp[] = [
  // ── Pocono Mountains, PA ─────────────────────────────────────────────
  {
    slug: "trails-end-camp",
    name: "Trail's End Camp",
    type: "sleepaway",
    city: "Beach Lake",
    state: "PA",
    region: "northeast",
    lat: 41.6,
    lng: -75.15,
    ageMin: 7,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [7],
    tuitionMin: 13500,
    tuitionMax: 16500,
    size: 550,
    founded: 1947,
    interests: ["team-sports", "arts-theater", "waterfront", "stem", "gymnastics-dance"],
    vibe: 5,
    competitiveness: 3,
    structure: 4,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A full-summer coed camp in the Poconos known for modern facilities, an elective-driven program and standout food. Big theater and athletics alongside a warm, spirited community.",
    website: "https://www.trailsendcampforkids.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-towanda",
    name: "Camp Towanda",
    type: "sleepaway",
    city: "Honesdale",
    state: "PA",
    region: "northeast",
    lat: 41.62,
    lng: -75.22,
    ageMin: 7,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [7],
    tuitionMin: 13000,
    tuitionMax: 15500,
    size: 450,
    founded: 1923,
    interests: ["team-sports", "waterfront", "arts-theater", "outdoor-adventure"],
    vibe: 3,
    competitiveness: 3,
    structure: 2,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A century-old, fiercely traditional full-summer camp famous for its spirit, color war and unplugged philosophy. Multi-generational families return year after year.",
    website: "https://www.camptowanda.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-ihc",
    name: "Camp IHC (Indian Head Camp)",
    type: "sleepaway",
    city: "Equinunk",
    state: "PA",
    region: "northeast",
    lat: 41.86,
    lng: -75.24,
    ageMin: 7,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [7],
    tuitionMin: 14000,
    tuitionMax: 16500,
    size: 500,
    founded: 1930,
    interests: ["team-sports", "waterfront", "arts-theater", "outdoor-adventure", "gymnastics-dance"],
    vibe: 5,
    competitiveness: 3,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A design-forward Poconos camp with a huge social-media following, gorgeous grounds and a culture built around joy and inclusivity. Full-summer only.",
    website: "https://www.campihc.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "lake-bryn-mawr-camp",
    name: "Lake Bryn Mawr Camp",
    type: "sleepaway",
    city: "Honesdale",
    state: "PA",
    region: "northeast",
    lat: 41.55,
    lng: -75.25,
    ageMin: 7,
    ageMax: 16,
    gender: "girls",
    sessionWeeks: [7],
    tuitionMin: 14000,
    tuitionMax: 16500,
    size: 400,
    founded: 1921,
    interests: ["horseback", "gymnastics-dance", "arts-theater", "waterfront", "team-sports"],
    vibe: 4,
    competitiveness: 3,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A premier all-girls camp on 250 hilltop acres with a storied equestrian program, strong arts and a century of sisterhood traditions.",
    website: "https://www.campbrynmawr.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-wayne",
    name: "Camp Wayne for Boys & Girls",
    type: "sleepaway",
    city: "Preston Park",
    state: "PA",
    region: "northeast",
    lat: 41.87,
    lng: -75.35,
    ageMin: 6,
    ageMax: 16,
    gender: "brother-sister",
    sessionWeeks: [4, 7],
    tuitionMin: 8500,
    tuitionMax: 14500,
    size: 400,
    founded: 1921,
    interests: ["team-sports", "waterfront", "arts-theater", "nature-animals"],
    vibe: 3,
    competitiveness: 2,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "Classic brother/sister camps on adjacent campuses — siblings share a lake and special events while keeping their own programs. Half-summer options make it a gentle on-ramp.",
    website: "https://www.campwayne.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "pine-forest-camp",
    name: "Pine Forest Camp",
    type: "sleepaway",
    city: "Greeley",
    state: "PA",
    region: "northeast",
    lat: 41.42,
    lng: -75.03,
    ageMin: 6,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [3.5, 7],
    tuitionMin: 8000,
    tuitionMax: 14000,
    size: 400,
    founded: 1931,
    interests: ["team-sports", "waterfront", "arts-theater", "outdoor-adventure"],
    vibe: 3,
    competitiveness: 2,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A warm, family-run Poconos institution (same family since 1931) with classic traditions, flexible sessions and a famously welcoming culture for first-time campers.",
    website: "https://www.pineforestcamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-canadensis",
    name: "Camp Canadensis",
    type: "sleepaway",
    city: "Canadensis",
    state: "PA",
    region: "northeast",
    lat: 41.19,
    lng: -75.25,
    ageMin: 7,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [7],
    tuitionMin: 13000,
    tuitionMax: 15500,
    size: 475,
    founded: 1941,
    interests: ["team-sports", "waterfront", "stem", "arts-theater", "outdoor-adventure"],
    vibe: 4,
    competitiveness: 3,
    structure: 4,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A full-summer coed camp balancing top athletics with a large elective program — campers build their own schedules as they get older.",
    website: "https://www.canadensis.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-nock-a-mixon",
    name: "Camp Nock-A-Mixon",
    type: "sleepaway",
    city: "Kintnersville",
    state: "PA",
    region: "mid-atlantic",
    lat: 40.55,
    lng: -75.2,
    ageMin: 7,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [4, 7],
    tuitionMin: 9000,
    tuitionMax: 15000,
    size: 425,
    founded: 1938,
    interests: ["team-sports", "waterfront", "arts-theater", "gymnastics-dance"],
    vibe: 4,
    competitiveness: 3,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "An upper-Bucks-County camp barely 90 minutes from North Jersey, known for excellent facilities, strong tennis and a close-knit feel with half-summer options.",
    website: "https://www.campnockamixon.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-lohikan",
    name: "Camp Lohikan",
    type: "sleepaway",
    city: "Lake Como",
    state: "PA",
    region: "northeast",
    lat: 41.87,
    lng: -75.32,
    ageMin: 6,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [2, 3, 4, 6, 7],
    tuitionMin: 4800,
    tuitionMax: 14000,
    size: 500,
    founded: 1957,
    interests: ["horseback", "waterfront", "team-sports", "action-sports", "nature-animals", "arts-theater"],
    vibe: 3,
    competitiveness: 1,
    structure: 5,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "Over 90 elective activities from horseback to wakeboarding, with flexible 2–7 week sessions and no religious affiliation — one of the easiest camps to try for a first summer.",
    website: "https://www.lohikan.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-weequahic",
    name: "Camp Weequahic",
    type: "sleepaway",
    city: "Lakewood",
    state: "PA",
    region: "northeast",
    lat: 41.83,
    lng: -75.38,
    ageMin: 7,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [2, 4],
    tuitionMin: 5500,
    tuitionMax: 10500,
    size: 350,
    founded: 1953,
    interests: ["team-sports", "waterfront", "arts-theater", "stem"],
    vibe: 4,
    competitiveness: 2,
    structure: 4,
    religious: "none",
    supports: ["food-allergies", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A two- and four-week coed camp built around gratitude, attitude and courage — shorter sessions and intentional culture make it a favorite for first-time campers.",
    website: "https://www.weequahic.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-starlight",
    name: "Camp Starlight",
    type: "sleepaway",
    city: "Starlight",
    state: "PA",
    region: "northeast",
    lat: 41.9,
    lng: -75.34,
    ageMin: 7,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [7],
    tuitionMin: 13500,
    tuitionMax: 16000,
    size: 500,
    founded: 1947,
    interests: ["team-sports", "waterfront", "arts-theater", "outdoor-adventure"],
    vibe: 4,
    competitiveness: 3,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "A full-summer brother/sister-style coed camp on a private lake with polished athletics, waterskiing and big production theater.",
    website: "https://www.campstarlight.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-ramah-poconos",
    name: "Camp Ramah in the Poconos",
    type: "sleepaway",
    city: "Lakewood",
    state: "PA",
    region: "northeast",
    lat: 41.84,
    lng: -75.4,
    ageMin: 8,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [4, 8],
    tuitionMin: 6500,
    tuitionMax: 12500,
    size: 400,
    founded: 1950,
    interests: ["team-sports", "waterfront", "arts-theater", "music", "nature-animals"],
    vibe: 2,
    competitiveness: 1,
    structure: 3,
    religious: "jewish-observant",
    supports: ["food-allergies", "inclusion-program"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "Conservative-movement Jewish camping with kosher dining, Shabbat, Hebrew woven into camp life, and a nationally respected Tikvah inclusion program.",
    website: "https://www.ramahpoconos.org",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-morasha",
    name: "Camp Morasha",
    type: "sleepaway",
    city: "Lakewood",
    state: "PA",
    region: "northeast",
    lat: 41.85,
    lng: -75.36,
    ageMin: 8,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [4, 8],
    tuitionMin: 6000,
    tuitionMax: 11500,
    size: 700,
    founded: 1964,
    interests: ["team-sports", "waterfront", "music", "outdoor-adventure"],
    vibe: 3,
    competitiveness: 3,
    structure: 2,
    religious: "jewish-observant",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A Modern Orthodox camp combining serious sports and waterfront with daily learning, kosher food and a vibrant Shabbat culture.",
    website: "https://www.morasha.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-harlam",
    name: "URJ Camp Harlam",
    type: "sleepaway",
    city: "Kunkletown",
    state: "PA",
    region: "northeast",
    lat: 40.92,
    lng: -75.43,
    ageMin: 8,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [3.5, 7],
    tuitionMin: 5500,
    tuitionMax: 11000,
    size: 550,
    founded: 1958,
    interests: ["music", "arts-theater", "team-sports", "waterfront", "nature-animals"],
    vibe: 3,
    competitiveness: 1,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies", "inclusion-program", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "The Reform movement's flagship Pennsylvania camp — song sessions, community values and joyful Judaism at a friendlier price point than private camps.",
    website: "https://camps.urj.org/harlam",
    claimed: false,
    verified: false,
  },
  {
    slug: "woodward-pa",
    name: "Camp Woodward",
    type: "sleepaway",
    city: "Woodward",
    state: "PA",
    region: "mid-atlantic",
    lat: 40.92,
    lng: -77.33,
    ageMin: 7,
    ageMax: 17,
    gender: "coed",
    sessionWeeks: [1, 2, 3],
    tuitionMin: 2200,
    tuitionMax: 6600,
    size: 900,
    founded: 1970,
    interests: ["action-sports", "gymnastics-dance", "stem"],
    vibe: 5,
    competitiveness: 4,
    structure: 5,
    religious: "none",
    supports: [],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "The world's most famous action-sports camp: skate, BMX, scooter, parkour, cheer and digital media on Olympic-grade facilities, in flexible one-week blocks.",
    website: "https://www.campwoodward.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "independent-lake-camp",
    name: "Independent Lake Camp",
    type: "sleepaway",
    city: "Thompson",
    state: "PA",
    region: "northeast",
    lat: 41.86,
    lng: -75.49,
    ageMin: 6,
    ageMax: 17,
    gender: "coed",
    sessionWeeks: [2, 4, 6, 8],
    tuitionMin: 5200,
    tuitionMax: 13500,
    size: 350,
    founded: 1991,
    interests: ["arts-theater", "music", "stem", "action-sports", "individual-sports", "horseback"],
    vibe: 3,
    competitiveness: 1,
    structure: 5,
    religious: "none",
    supports: ["food-allergies", "adhd-learning", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A creative, choice-driven camp where kids fully design their own schedules — beloved by artsy, quirky and independent kids who don't fit the classic sports-camp mold.",
    website: "https://www.independentlake.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "summit-camp",
    name: "Summit Camp",
    type: "sleepaway",
    city: "Honesdale",
    state: "PA",
    region: "northeast",
    lat: 41.66,
    lng: -75.3,
    ageMin: 7,
    ageMax: 17,
    gender: "coed",
    sessionWeeks: [3, 6],
    tuitionMin: 7500,
    tuitionMax: 14500,
    size: 250,
    founded: 1969,
    interests: ["nature-animals", "stem", "arts-theater", "waterfront", "team-sports"],
    vibe: 3,
    competitiveness: 1,
    structure: 2,
    religious: "none",
    supports: ["adhd-learning", "anxiety-support", "inclusion-program", "food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A pioneering camp for kids with ADHD, autism-spectrum profiles and social-learning differences — full traditional camp fun with high staffing ratios and clinical support.",
    website: "https://www.summitcamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-lee-mar",
    name: "Camp Lee Mar",
    type: "sleepaway",
    city: "Lackawaxen",
    state: "PA",
    region: "northeast",
    lat: 41.48,
    lng: -75.01,
    ageMin: 7,
    ageMax: 21,
    gender: "coed",
    sessionWeeks: [7],
    tuitionMin: 12000,
    tuitionMax: 14000,
    size: 200,
    founded: 1953,
    interests: ["nature-animals", "arts-theater", "waterfront", "music"],
    vibe: 3,
    competitiveness: 1,
    structure: 1,
    religious: "none",
    supports: ["inclusion-program", "adhd-learning", "food-allergies", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A warm, structured camp for children with developmental disabilities, blending speech and academics with classic camp activities since 1953.",
    website: "https://www.leemar.com",
    claimed: false,
    verified: false,
  },

  // ── New York ─────────────────────────────────────────────────────────
  {
    slug: "timber-lake-camp",
    name: "Timber Lake Camp",
    type: "sleepaway",
    city: "Shandaken",
    state: "NY",
    region: "northeast",
    lat: 42.12,
    lng: -74.4,
    ageMin: 7,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [7],
    tuitionMin: 14000,
    tuitionMax: 16500,
    size: 450,
    founded: 1962,
    interests: ["team-sports", "waterfront", "arts-theater", "gymnastics-dance"],
    vibe: 5,
    competitiveness: 3,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A polished full-summer Catskills camp just two hours from North Jersey, with premier facilities and a long list of celebrity alumni.",
    website: "https://www.timberlakecamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-schodack",
    name: "Camp Schodack",
    type: "sleepaway",
    city: "Nassau",
    state: "NY",
    region: "northeast",
    lat: 42.5,
    lng: -73.6,
    ageMin: 7,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [3.5, 7],
    tuitionMin: 8500,
    tuitionMax: 14500,
    size: 350,
    founded: 1957,
    interests: ["team-sports", "waterfront", "arts-theater", "nature-animals"],
    vibe: 3,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A family-run camp near Albany praised for emotional safety and community — a strong pick for kids who need warmth over flash, with half-summer options.",
    website: "https://www.schodack.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "brant-lake-camp",
    name: "Brant Lake Camp",
    type: "sleepaway",
    city: "Brant Lake",
    state: "NY",
    region: "northeast",
    lat: 43.7,
    lng: -73.71,
    ageMin: 7,
    ageMax: 15,
    gender: "boys",
    sessionWeeks: [3.5, 7],
    tuitionMin: 9500,
    tuitionMax: 17000,
    size: 400,
    founded: 1916,
    interests: ["team-sports", "waterfront", "individual-sports"],
    vibe: 3,
    competitiveness: 4,
    structure: 2,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "One of America's classic boys' camps, on Brant Lake in the Adirondacks since 1916 — serious athletics, deep traditions and third-generation campers.",
    website: "https://www.brantlake.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "point-o-pines",
    name: "Point O'Pines Camp for Girls",
    type: "sleepaway",
    city: "Brant Lake",
    state: "NY",
    region: "northeast",
    lat: 43.71,
    lng: -73.7,
    ageMin: 7,
    ageMax: 16,
    gender: "girls",
    sessionWeeks: [7],
    tuitionMin: 15000,
    tuitionMax: 17500,
    size: 300,
    founded: 1957,
    interests: ["horseback", "waterfront", "team-sports", "arts-theater", "gymnastics-dance"],
    vibe: 4,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "An all-girls Adirondack camp on a private peninsula — riding, waterskiing and a tight sisterhood, run by the same family for decades.",
    website: "https://www.pointopines.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "raquette-lake-camps",
    name: "Raquette Lake Camps",
    type: "sleepaway",
    city: "Raquette Lake",
    state: "NY",
    region: "northeast",
    lat: 43.81,
    lng: -74.65,
    ageMin: 7,
    ageMax: 15,
    gender: "brother-sister",
    sessionWeeks: [7],
    tuitionMin: 15500,
    tuitionMax: 18000,
    size: 350,
    founded: 1916,
    interests: ["waterfront", "team-sports", "arts-theater", "outdoor-adventure", "horseback"],
    vibe: 4,
    competitiveness: 3,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "Historic brother/sister camps across a pristine Adirondack lake, mixing luxury facilities with deep-woods tradition.",
    website: "https://www.raquettelake.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-echo-lake",
    name: "Camp Echo Lake",
    type: "sleepaway",
    city: "Warrensburg",
    state: "NY",
    region: "northeast",
    lat: 43.5,
    lng: -73.78,
    ageMin: 7,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [7],
    tuitionMin: 13500,
    tuitionMax: 15800,
    size: 450,
    founded: 1946,
    interests: ["team-sports", "waterfront", "arts-theater", "outdoor-adventure", "music"],
    vibe: 3,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A values-driven Adirondack coed camp known for youth-development chops — staff training and camper wellbeing are the product, not an afterthought.",
    website: "https://www.campecholake.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "french-woods",
    name: "French Woods Festival of the Performing Arts",
    type: "sleepaway",
    city: "Hancock",
    state: "NY",
    region: "northeast",
    lat: 41.98,
    lng: -75.19,
    ageMin: 7,
    ageMax: 17,
    gender: "coed",
    sessionWeeks: [3, 6, 9],
    tuitionMin: 5500,
    tuitionMax: 16000,
    size: 800,
    founded: 1970,
    interests: ["arts-theater", "music", "gymnastics-dance", "action-sports", "stem"],
    vibe: 3,
    competitiveness: 2,
    structure: 5,
    religious: "none",
    supports: ["food-allergies", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "The country's best-known performing-arts camp — full musical productions every three weeks, plus circus, rock bands, magic and film, all self-scheduled.",
    website: "https://www.frenchwoods.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "long-lake-camp-arts",
    name: "Long Lake Camp for the Arts",
    type: "sleepaway",
    city: "Long Lake",
    state: "NY",
    region: "northeast",
    lat: 43.97,
    lng: -74.42,
    ageMin: 9,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [2, 3, 6],
    tuitionMin: 5000,
    tuitionMax: 13500,
    size: 250,
    founded: 1969,
    interests: ["arts-theater", "music", "gymnastics-dance", "waterfront"],
    vibe: 2,
    competitiveness: 1,
    structure: 5,
    religious: "none",
    supports: ["food-allergies", "anxiety-support", "adhd-learning"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "An intimate Adirondack arts camp where every kid gets cast — theater, film, fine arts and music with total creative freedom and short-session flexibility.",
    website: "https://www.longlakecamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-ramah-berkshires",
    name: "Camp Ramah in the Berkshires",
    type: "sleepaway",
    city: "Wingdale",
    state: "NY",
    region: "northeast",
    lat: 41.65,
    lng: -73.57,
    ageMin: 8,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [4, 8],
    tuitionMin: 6500,
    tuitionMax: 13000,
    size: 550,
    founded: 1961,
    interests: ["team-sports", "waterfront", "music", "arts-theater", "outdoor-adventure"],
    vibe: 2,
    competitiveness: 2,
    structure: 2,
    religious: "jewish-observant",
    supports: ["food-allergies", "inclusion-program"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "Conservative Jewish camping 90 minutes from North Jersey — kosher, Shabbat-observant, with strong sports and the Breira/Tikvah inclusion tracks.",
    website: "https://www.ramahberkshires.org",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-dudley",
    name: "Camp Dudley",
    type: "sleepaway",
    city: "Westport",
    state: "NY",
    region: "northeast",
    lat: 44.16,
    lng: -73.44,
    ageMin: 10,
    ageMax: 15,
    gender: "boys",
    sessionWeeks: [2, 4],
    tuitionMin: 3400,
    tuitionMax: 9800,
    size: 500,
    founded: 1885,
    interests: ["team-sports", "waterfront", "outdoor-adventure", "arts-theater", "music"],
    vibe: 1,
    competitiveness: 2,
    structure: 2,
    religious: "christian",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "The oldest continuously running boys' camp in America (1885). 'The Other Fellow First' ethos, Lake Champlain setting and generous financial aid.",
    website: "https://www.campdudley.org",
    claimed: false,
    verified: false,
  },

  // ── Maine ────────────────────────────────────────────────────────────
  {
    slug: "camp-takajo",
    name: "Camp Takajo",
    type: "sleepaway",
    city: "Naples",
    state: "ME",
    region: "northeast",
    lat: 43.94,
    lng: -70.6,
    ageMin: 7,
    ageMax: 15,
    gender: "boys",
    sessionWeeks: [7],
    tuitionMin: 15500,
    tuitionMax: 17500,
    size: 400,
    founded: 1947,
    interests: ["team-sports", "waterfront", "individual-sports", "outdoor-adventure"],
    vibe: 3,
    competitiveness: 4,
    structure: 2,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "A blue-chip boys' camp on Long Lake, Maine — full-summer, sports-forward and tradition-rich, with values (honor, humility) taken seriously.",
    website: "https://www.takajo.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-vega",
    name: "Camp Vega",
    type: "sleepaway",
    city: "Fayette",
    state: "ME",
    region: "northeast",
    lat: 44.4,
    lng: -70.08,
    ageMin: 7,
    ageMax: 15,
    gender: "girls",
    sessionWeeks: [7],
    tuitionMin: 15500,
    tuitionMax: 17500,
    size: 350,
    founded: 1936,
    interests: ["waterfront", "team-sports", "horseback", "gymnastics-dance", "arts-theater"],
    vibe: 4,
    competitiveness: 3,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "A premier all-girls camp on Echo Lake with world-class waterskiing, riding and a sisterhood that alumnae describe as lifelong.",
    website: "https://www.campvega.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "tripp-lake-camp",
    name: "Tripp Lake Camp",
    type: "sleepaway",
    city: "Poland",
    state: "ME",
    region: "northeast",
    lat: 44.06,
    lng: -70.39,
    ageMin: 7,
    ageMax: 15,
    gender: "girls",
    sessionWeeks: [7],
    tuitionMin: 15500,
    tuitionMax: 17500,
    size: 330,
    founded: 1911,
    interests: ["team-sports", "gymnastics-dance", "waterfront", "horseback", "arts-theater"],
    vibe: 3,
    competitiveness: 4,
    structure: 2,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "One of the oldest girls' camps in the country and among its most athletic — a century of tradition, team spirit and full-summer immersion.",
    website: "https://www.tripplakecamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-laurel",
    name: "Camp Laurel",
    type: "sleepaway",
    city: "Readfield",
    state: "ME",
    region: "northeast",
    lat: 44.42,
    lng: -69.98,
    ageMin: 7,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [7],
    tuitionMin: 15500,
    tuitionMax: 17500,
    size: 450,
    founded: 1949,
    interests: ["team-sports", "waterfront", "horseback", "arts-theater", "individual-sports"],
    vibe: 5,
    competitiveness: 3,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "A full-summer coed camp on Echo Lake with resort-grade facilities — often mentioned in the same breath as Maine's single-gender giants, but coed.",
    website: "https://www.camplaurel.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-manitou",
    name: "Camp Manitou",
    type: "sleepaway",
    city: "Oakland",
    state: "ME",
    region: "northeast",
    lat: 44.56,
    lng: -69.75,
    ageMin: 7,
    ageMax: 16,
    gender: "boys",
    sessionWeeks: [3.5, 7],
    tuitionMin: 9500,
    tuitionMax: 16500,
    size: 400,
    founded: 1947,
    interests: ["team-sports", "waterfront", "outdoor-adventure", "individual-sports", "stem"],
    vibe: 4,
    competitiveness: 3,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A top boys' camp in the Belgrade Lakes with half-summer entry options — strong sports without the cutthroat edge, and a big brotherhood culture.",
    website: "https://www.campmanitou.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-skylemar",
    name: "Camp Skylemar",
    type: "sleepaway",
    city: "Naples",
    state: "ME",
    region: "northeast",
    lat: 43.97,
    lng: -70.62,
    ageMin: 7,
    ageMax: 16,
    gender: "boys",
    sessionWeeks: [3.5, 7],
    tuitionMin: 9500,
    tuitionMax: 16500,
    size: 220,
    founded: 1949,
    interests: ["team-sports", "individual-sports", "waterfront", "outdoor-adventure"],
    vibe: 3,
    competitiveness: 3,
    structure: 2,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A deliberately small boys' camp (about 220 campers) where every kid is known by name — excellent golf and sports instruction with a family feel.",
    website: "https://www.skylemar.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-matoaka",
    name: "Camp Matoaka",
    type: "sleepaway",
    city: "Smithfield",
    state: "ME",
    region: "northeast",
    lat: 44.63,
    lng: -69.81,
    ageMin: 7,
    ageMax: 15,
    gender: "girls",
    sessionWeeks: [7],
    tuitionMin: 15000,
    tuitionMax: 17000,
    size: 330,
    founded: 1951,
    interests: ["waterfront", "team-sports", "arts-theater", "gymnastics-dance", "horseback"],
    vibe: 4,
    competitiveness: 3,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "An all-girls camp on East Pond known for spirit, waterfront depth and all-camp traditions like Harry Potter Day and 4th of July extravaganzas.",
    website: "https://www.matoaka.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-modin",
    name: "Camp Modin",
    type: "sleepaway",
    city: "Belgrade",
    state: "ME",
    region: "northeast",
    lat: 44.45,
    lng: -69.83,
    ageMin: 8,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [3.5, 7],
    tuitionMin: 10000,
    tuitionMax: 16500,
    size: 300,
    founded: 1922,
    interests: ["waterfront", "team-sports", "arts-theater", "outdoor-adventure"],
    vibe: 4,
    competitiveness: 2,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "New England's oldest Jewish camp (1922), now a modern coed camp with kosher-style dining, a stunning Belgrade Lakes setting and half-summer options.",
    website: "https://www.modin.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-winnebago",
    name: "Camp Winnebago",
    type: "sleepaway",
    city: "Fayette",
    state: "ME",
    region: "northeast",
    lat: 44.41,
    lng: -70.07,
    ageMin: 8,
    ageMax: 15,
    gender: "boys",
    sessionWeeks: [3.5, 7],
    tuitionMin: 9800,
    tuitionMax: 16800,
    size: 200,
    founded: 1919,
    interests: ["team-sports", "waterfront", "outdoor-adventure", "nature-animals", "individual-sports"],
    vibe: 2,
    competitiveness: 2,
    structure: 2,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A small, screen-free boys' camp on Echo Lake since 1919 — unhurried, tradition-steeped and intentionally low-tech, with trips into the Maine woods.",
    website: "https://www.campwinnebago.com",
    claimed: false,
    verified: false,
  },

  // ── New England (MA / NH / VT / CT) ──────────────────────────────────
  {
    slug: "camp-winadu",
    name: "Camp Winadu",
    type: "sleepaway",
    city: "Pittsfield",
    state: "MA",
    region: "northeast",
    lat: 42.45,
    lng: -73.28,
    ageMin: 7,
    ageMax: 15,
    gender: "boys",
    sessionWeeks: [7],
    tuitionMin: 14500,
    tuitionMax: 16800,
    size: 400,
    founded: 1922,
    interests: ["team-sports", "individual-sports", "waterfront"],
    vibe: 4,
    competitiveness: 5,
    structure: 2,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "A Berkshires boys' camp with pro-grade athletic facilities and coaching — the pick for the kid who lives and breathes sports.",
    website: "https://www.campwinadu.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-danbee",
    name: "Camp Danbee",
    type: "sleepaway",
    city: "Hinsdale",
    state: "MA",
    region: "northeast",
    lat: 42.44,
    lng: -73.12,
    ageMin: 7,
    ageMax: 15,
    gender: "girls",
    sessionWeeks: [7],
    tuitionMin: 14000,
    tuitionMax: 16500,
    size: 400,
    founded: 1950,
    interests: ["team-sports", "gymnastics-dance", "waterfront", "arts-theater"],
    vibe: 4,
    competitiveness: 3,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "An energetic all-girls camp in the Berkshires — big on spirit, athletics and lifelong friendships, a sister-camp counterpart to Winadu.",
    website: "https://www.danbee.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-greylock",
    name: "Camp Greylock",
    type: "sleepaway",
    city: "Becket",
    state: "MA",
    region: "northeast",
    lat: 42.31,
    lng: -73.08,
    ageMin: 7,
    ageMax: 15,
    gender: "boys",
    sessionWeeks: [7],
    tuitionMin: 14500,
    tuitionMax: 17000,
    size: 350,
    founded: 1916,
    interests: ["team-sports", "individual-sports", "waterfront", "outdoor-adventure"],
    vibe: 3,
    competitiveness: 5,
    structure: 2,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "One of the country's most storied boys' sports camps (est. 1916) — basketball royalty, full-summer immersion and a century of Berkshires tradition.",
    website: "https://www.campgreylock.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-romaca",
    name: "Camp Romaca",
    type: "sleepaway",
    city: "Hinsdale",
    state: "MA",
    region: "northeast",
    lat: 42.42,
    lng: -73.13,
    ageMin: 7,
    ageMax: 15,
    gender: "girls",
    sessionWeeks: [3.5, 7],
    tuitionMin: 9000,
    tuitionMax: 15500,
    size: 250,
    founded: 1929,
    interests: ["team-sports", "waterfront", "arts-theater", "gymnastics-dance"],
    vibe: 3,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A close-knit girls' camp on a private Berkshires lake offering half-summer sessions — warm, unpretentious and great for first-time campers.",
    website: "https://www.campromaca.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-watitoh",
    name: "Camp Watitoh",
    type: "sleepaway",
    city: "Becket",
    state: "MA",
    region: "northeast",
    lat: 42.33,
    lng: -73.09,
    ageMin: 7,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [3.5, 7],
    tuitionMin: 8500,
    tuitionMax: 14500,
    size: 250,
    founded: 1937,
    interests: ["waterfront", "team-sports", "arts-theater", "nature-animals"],
    vibe: 2,
    competitiveness: 2,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A small family-owned coed camp in the Berkshires where three generations of the same families keep coming back — intimate, classic and friendly.",
    website: "https://www.campwatitoh.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-walt-whitman",
    name: "Camp Walt Whitman",
    type: "sleepaway",
    city: "Piermont",
    state: "NH",
    region: "northeast",
    lat: 44.03,
    lng: -72.08,
    ageMin: 7,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [3.5, 7],
    tuitionMin: 9800,
    tuitionMax: 16500,
    size: 400,
    founded: 1948,
    interests: ["team-sports", "waterfront", "outdoor-adventure", "arts-theater"],
    vibe: 3,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A White Mountains coed camp with a national reputation for kindness culture and camper development — hiking 4,000-footers is a rite of passage.",
    website: "https://www.campwalt.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-wicosuta",
    name: "Camp Wicosuta",
    type: "sleepaway",
    city: "Hebron",
    state: "NH",
    region: "northeast",
    lat: 43.7,
    lng: -71.81,
    ageMin: 7,
    ageMax: 15,
    gender: "girls",
    sessionWeeks: [2, 4],
    tuitionMin: 6500,
    tuitionMax: 11500,
    size: 350,
    founded: 1920,
    interests: ["team-sports", "waterfront", "arts-theater", "gymnastics-dance", "horseback"],
    vibe: 4,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A confidence-focused girls' camp on Newfound Lake with two- and four-week sessions — 'Wico confidence' is the whole point.",
    website: "https://www.campwicosuta.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-tecumseh-nh",
    name: "Camp Tecumseh",
    type: "sleepaway",
    city: "Moultonborough",
    state: "NH",
    region: "northeast",
    lat: 43.71,
    lng: -71.4,
    ageMin: 8,
    ageMax: 15,
    gender: "boys",
    sessionWeeks: [3.5, 7],
    tuitionMin: 8500,
    tuitionMax: 15500,
    size: 220,
    founded: 1903,
    interests: ["team-sports", "waterfront", "individual-sports", "outdoor-adventure"],
    vibe: 1,
    competitiveness: 4,
    structure: 2,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: false,
    acaAccredited: true,
    description:
      "A famously rustic boys' camp on Lake Winnipesaukee (est. 1903) — old-school sportsmanship, no frills, and traditions measured in generations.",
    website: "https://www.camptecumseh.net",
    claimed: false,
    verified: false,
  },
  {
    slug: "urj-eisner-camp",
    name: "URJ Eisner Camp",
    type: "sleepaway",
    city: "Great Barrington",
    state: "MA",
    region: "northeast",
    lat: 42.19,
    lng: -73.36,
    ageMin: 8,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [3.5, 7],
    tuitionMin: 5800,
    tuitionMax: 11500,
    size: 600,
    founded: 1958,
    interests: ["music", "arts-theater", "team-sports", "waterfront", "nature-animals"],
    vibe: 3,
    competitiveness: 1,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies", "inclusion-program", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A joyful Reform Jewish camp in the Berkshires — song-filled Shabbats, farm-to-table garden program and a big warm community.",
    website: "https://eisner.urjcamps.org",
    claimed: false,
    verified: false,
  },

  // ── South ────────────────────────────────────────────────────────────
  {
    slug: "camp-longhorn",
    name: "Camp Longhorn",
    type: "sleepaway",
    city: "Burnet",
    state: "TX",
    region: "south",
    lat: 30.75,
    lng: -98.32,
    ageMin: 8,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [2, 3],
    tuitionMin: 2900,
    tuitionMax: 5200,
    size: 800,
    founded: 1939,
    interests: ["waterfront", "team-sports", "outdoor-adventure", "nature-animals"],
    vibe: 3,
    competitiveness: 3,
    structure: 2,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A Texas Hill Country institution on Inks Lake — 'Attaway to go!' spirit, merit system and waiting lists that start at birth.",
    website: "https://www.camplonghorn.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-champions",
    name: "Camp Champions",
    type: "sleepaway",
    city: "Marble Falls",
    state: "TX",
    region: "south",
    lat: 30.59,
    lng: -98.26,
    ageMin: 6,
    ageMax: 18,
    gender: "coed",
    sessionWeeks: [1, 2, 3],
    tuitionMin: 1900,
    tuitionMax: 6500,
    size: 600,
    founded: 1967,
    interests: ["waterfront", "team-sports", "outdoor-adventure", "stem", "horseback"],
    vibe: 4,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A growth-mindset coed camp on Lake LBJ in Texas — intentional character development wrapped in wakeboarding, blobs and Hill Country fun.",
    website: "https://www.campchampions.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-ozark",
    name: "Camp Ozark",
    type: "sleepaway",
    city: "Mount Ida",
    state: "AR",
    region: "south",
    lat: 34.55,
    lng: -93.63,
    ageMin: 7,
    ageMax: 17,
    gender: "coed",
    sessionWeeks: [1, 2, 3, 4],
    tuitionMin: 1800,
    tuitionMax: 7500,
    size: 1000,
    founded: 1985,
    interests: ["waterfront", "team-sports", "outdoor-adventure", "action-sports", "horseback"],
    vibe: 4,
    competitiveness: 3,
    structure: 3,
    religious: "christian",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A high-energy Christian sports and adventure camp in the Ouachita Mountains with flexible session lengths and 60+ activities.",
    website: "https://www.campozark.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "falling-creek-camp",
    name: "Falling Creek Camp",
    type: "sleepaway",
    city: "Zirconia",
    state: "NC",
    region: "south",
    lat: 35.22,
    lng: -82.42,
    ageMin: 6,
    ageMax: 16,
    gender: "boys",
    sessionWeeks: [1, 2, 3, 4],
    tuitionMin: 2200,
    tuitionMax: 9500,
    size: 400,
    founded: 1969,
    interests: ["outdoor-adventure", "waterfront", "team-sports", "nature-animals", "horseback"],
    vibe: 2,
    competitiveness: 2,
    structure: 4,
    religious: "christian",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A Blue Ridge boys' camp centered on outdoor adventure — mountain biking, climbing, whitewater — with a servant-leadership ethos.",
    website: "https://www.fallingcreek.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "rockbrook-camp",
    name: "Rockbrook Camp for Girls",
    type: "sleepaway",
    city: "Brevard",
    state: "NC",
    region: "south",
    lat: 35.21,
    lng: -82.73,
    ageMin: 6,
    ageMax: 16,
    gender: "girls",
    sessionWeeks: [2, 3, 4],
    tuitionMin: 3200,
    tuitionMax: 9000,
    size: 220,
    founded: 1921,
    interests: ["horseback", "outdoor-adventure", "arts-theater", "nature-animals", "waterfront"],
    vibe: 1,
    competitiveness: 1,
    structure: 4,
    religious: "none",
    supports: ["food-allergies", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A 100-year-old girls' camp in a stone-and-forest setting near Brevard — crafts, riding and whitewater in an intentionally noncompetitive culture.",
    website: "https://www.rockbrookcamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-greystone",
    name: "Camp Greystone",
    type: "sleepaway",
    city: "Tuxedo",
    state: "NC",
    region: "south",
    lat: 35.22,
    lng: -82.42,
    ageMin: 6,
    ageMax: 17,
    gender: "girls",
    sessionWeeks: [1, 2, 3, 5],
    tuitionMin: 2500,
    tuitionMax: 11000,
    size: 550,
    founded: 1920,
    interests: ["waterfront", "gymnastics-dance", "arts-theater", "horseback", "team-sports"],
    vibe: 4,
    competitiveness: 2,
    structure: 3,
    religious: "christian",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A beloved Christian girls' camp in the North Carolina mountains — polished program, famous food and a century of 'Greystone girls.'",
    website: "https://www.campgreystone.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-highlander",
    name: "Camp Highlander",
    type: "sleepaway",
    city: "Mills River",
    state: "NC",
    region: "south",
    lat: 35.39,
    lng: -82.57,
    ageMin: 6,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [1, 2, 3, 4],
    tuitionMin: 2100,
    tuitionMax: 8500,
    size: 350,
    founded: 1957,
    interests: ["outdoor-adventure", "waterfront", "horseback", "team-sports", "arts-theater"],
    vibe: 3,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A coed Blue Ridge camp with flexible sessions, mountain adventure and a warm, unaffiliated community — an easy first sleepaway experience.",
    website: "https://www.camphighlander.com",
    claimed: false,
    verified: false,
  },

  // ── Midwest & West ───────────────────────────────────────────────────
  {
    slug: "interlochen-arts-camp",
    name: "Interlochen Arts Camp",
    type: "sleepaway",
    city: "Interlochen",
    state: "MI",
    region: "midwest",
    lat: 44.64,
    lng: -85.77,
    ageMin: 8,
    ageMax: 18,
    gender: "coed",
    sessionWeeks: [1, 2, 3, 4, 6],
    tuitionMin: 2000,
    tuitionMax: 12500,
    size: 2500,
    founded: 1928,
    interests: ["music", "arts-theater", "gymnastics-dance", "stem"],
    vibe: 3,
    competitiveness: 4,
    structure: 1,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "The world's premier arts camp — conservatory-level music, theater, dance, film and creative writing among Michigan pines. Auditioned programs for serious young artists.",
    website: "https://camp.interlochen.org",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-foley",
    name: "Camp Foley",
    type: "sleepaway",
    city: "Pine River",
    state: "MN",
    region: "midwest",
    lat: 46.72,
    lng: -94.29,
    ageMin: 7,
    ageMax: 16,
    gender: "coed",
    sessionWeeks: [1, 2, 4],
    tuitionMin: 2400,
    tuitionMax: 9800,
    size: 200,
    founded: 1924,
    interests: ["waterfront", "outdoor-adventure", "nature-animals", "individual-sports", "horseback"],
    vibe: 2,
    competitiveness: 1,
    structure: 4,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A century-old Northwoods camp on Whitefish Lake — sailing, waterskiing and unplugged lake life in an intimate 200-camper community.",
    website: "https://www.campfoley.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "cheley-colorado-camps",
    name: "Cheley Colorado Camps",
    type: "sleepaway",
    city: "Estes Park",
    state: "CO",
    region: "west",
    lat: 40.35,
    lng: -105.51,
    ageMin: 9,
    ageMax: 17,
    gender: "brother-sister",
    sessionWeeks: [4, 8],
    tuitionMin: 6900,
    tuitionMax: 13500,
    size: 500,
    founded: 1921,
    interests: ["outdoor-adventure", "horseback", "nature-animals", "individual-sports"],
    vibe: 1,
    competitiveness: 1,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "Rocky Mountain camping at 8,000 feet beside Rocky Mountain National Park — backpacking, horsepacking and technical climbing since 1921.",
    website: "https://www.cheley.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "gold-arrow-camp",
    name: "Gold Arrow Camp",
    type: "sleepaway",
    city: "Lakeshore",
    state: "CA",
    region: "west",
    lat: 37.25,
    lng: -119.18,
    ageMin: 6,
    ageMax: 14,
    gender: "coed",
    sessionWeeks: [1, 2, 3.5],
    tuitionMin: 2600,
    tuitionMax: 9500,
    size: 350,
    founded: 1933,
    interests: ["waterfront", "outdoor-adventure", "horseback", "nature-animals"],
    vibe: 2,
    competitiveness: 1,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A Sierra Nevada classic on Huntington Lake — waterskiing, sailing and screen-free outdoor living in California's high country since 1933.",
    website: "https://www.goldarrowcamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "catalina-island-camps",
    name: "Catalina Island Camps",
    type: "sleepaway",
    city: "Two Harbors",
    state: "CA",
    region: "west",
    lat: 33.44,
    lng: -118.51,
    ageMin: 7,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [1, 2, 4],
    tuitionMin: 2400,
    tuitionMax: 9200,
    size: 250,
    founded: 1922,
    interests: ["waterfront", "nature-animals", "outdoor-adventure", "stem"],
    vibe: 2,
    competitiveness: 1,
    structure: 4,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "Ocean camping on Catalina Island — snorkeling, kayaking and marine science straight off the beach, a completely different flavor of summer camp.",
    website: "https://www.catalinaislandcamps.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "ymca-camp-orkila",
    name: "YMCA Camp Orkila",
    type: "sleepaway",
    city: "Orcas Island",
    state: "WA",
    region: "west",
    lat: 48.7,
    lng: -122.95,
    ageMin: 6,
    ageMax: 17,
    gender: "coed",
    sessionWeeks: [1, 2],
    tuitionMin: 1100,
    tuitionMax: 3800,
    size: 500,
    founded: 1906,
    interests: ["outdoor-adventure", "nature-animals", "waterfront", "horseback"],
    vibe: 1,
    competitiveness: 1,
    structure: 3,
    religious: "none",
    supports: ["food-allergies", "inclusion-program"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A Puget Sound YMCA camp on Orcas Island — tide pools, sea kayaking and big financial accessibility, running since 1906.",
    website: "https://www.seattleymca.org/camp-orkila",
    claimed: false,
    verified: false,
  },

  // ── New Jersey / NY metro day camps ──────────────────────────────────
  {
    slug: "willow-lake-day-camp",
    name: "Willow Lake Day Camp",
    type: "day",
    city: "Lake Hopatcong",
    state: "NJ",
    region: "mid-atlantic",
    lat: 40.94,
    lng: -74.62,
    ageMin: 3,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [4, 6, 8],
    tuitionMin: 4500,
    tuitionMax: 9500,
    size: 800,
    founded: 1957,
    interests: ["waterfront", "team-sports", "arts-theater", "action-sports", "nature-animals"],
    vibe: 4,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A full-facility North Jersey day camp on a private lake — transportation across Essex and Morris counties, huge aquatics program and decades of Livingston-area families.",
    website: "https://www.willowlake.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "spring-lake-day-camp",
    name: "Spring Lake Day Camp",
    type: "day",
    city: "Ringwood",
    state: "NJ",
    region: "mid-atlantic",
    lat: 41.11,
    lng: -74.27,
    ageMin: 3,
    ageMax: 14,
    gender: "coed",
    sessionWeeks: [4, 6, 8],
    tuitionMin: 4800,
    tuitionMax: 10000,
    size: 900,
    founded: 1989,
    interests: ["waterfront", "team-sports", "arts-theater", "gymnastics-dance", "stem"],
    vibe: 5,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A premier North Jersey day camp with resort-level pools, lake activities and door-to-door busing — polished, spirited and heavily subscribed.",
    website: "https://www.springlakedaycamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-riverbend",
    name: "Camp Riverbend",
    type: "day",
    city: "Warren",
    state: "NJ",
    region: "mid-atlantic",
    lat: 40.63,
    lng: -74.51,
    ageMin: 3,
    ageMax: 14,
    gender: "coed",
    sessionWeeks: [2, 4, 6, 8],
    tuitionMin: 2200,
    tuitionMax: 9000,
    size: 600,
    founded: 1959,
    interests: ["nature-animals", "waterfront", "team-sports", "arts-theater", "outdoor-adventure"],
    vibe: 3,
    competitiveness: 1,
    structure: 3,
    religious: "none",
    supports: ["food-allergies", "anxiety-support"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A family-run day camp on 30 wooded riverside acres in Somerset County — nature-forward, flexible enrollments and a famously gentle culture.",
    website: "https://www.campriverbend.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "harbor-hills-day-camp",
    name: "Harbor Hills Day Camp",
    type: "day",
    city: "Mendham",
    state: "NJ",
    region: "mid-atlantic",
    lat: 40.78,
    lng: -74.6,
    ageMin: 3,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [4, 8],
    tuitionMin: 4200,
    tuitionMax: 9200,
    size: 700,
    founded: 1961,
    interests: ["waterfront", "team-sports", "horseback", "arts-theater", "nature-animals"],
    vibe: 3,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A classic Morris County day camp on a private lake with horseback riding, boating and multi-generation staff continuity.",
    website: "https://www.harborhills.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "camp-deeny-riback",
    name: "JCC Camp Deeny Riback",
    type: "day",
    city: "Flanders",
    state: "NJ",
    region: "mid-atlantic",
    lat: 40.84,
    lng: -74.7,
    ageMin: 3,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [2, 4, 6, 8],
    tuitionMin: 1800,
    tuitionMax: 7500,
    size: 600,
    founded: 1965,
    interests: ["waterfront", "team-sports", "arts-theater", "music", "nature-animals"],
    vibe: 3,
    competitiveness: 1,
    structure: 3,
    religious: "jewish-cultural",
    supports: ["food-allergies", "inclusion-program"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "JCC MetroWest's day camp serving Essex and Morris counties — Jewish culture, big pools, flexible sessions and a respected inclusion program.",
    website: "https://www.jccmetrowest.org/camps",
    claimed: false,
    verified: false,
  },
  {
    slug: "rambling-pines-day-camp",
    name: "Rambling Pines Day Camp",
    type: "day",
    city: "Hopewell",
    state: "NJ",
    region: "mid-atlantic",
    lat: 40.39,
    lng: -74.77,
    ageMin: 3,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [2, 4, 6, 8],
    tuitionMin: 2000,
    tuitionMax: 8800,
    size: 700,
    founded: 1965,
    interests: ["team-sports", "waterfront", "horseback", "arts-theater", "action-sports"],
    vibe: 3,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A central-Jersey day camp on 100+ acres with horseback, go-karts and big aquatics — flexible weeks and busing across Mercer/Somerset.",
    website: "https://www.ramblingpines.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "breezemont-day-camp",
    name: "Breezemont Day Camp",
    type: "day",
    city: "Armonk",
    state: "NY",
    region: "northeast",
    lat: 41.13,
    lng: -73.71,
    ageMin: 3,
    ageMax: 14,
    gender: "coed",
    sessionWeeks: [4, 6, 8],
    tuitionMin: 5500,
    tuitionMax: 12000,
    size: 900,
    founded: 1935,
    interests: ["waterfront", "team-sports", "gymnastics-dance", "arts-theater", "stem"],
    vibe: 5,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A high-end Westchester day camp with country-club-grade facilities, elite swim instruction and full transportation.",
    website: "https://www.breezemont.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "deerkill-day-camp",
    name: "Deerkill Day Camp",
    type: "day",
    city: "Suffern",
    state: "NY",
    region: "northeast",
    lat: 41.13,
    lng: -74.1,
    ageMin: 3,
    ageMax: 14,
    gender: "coed",
    sessionWeeks: [2, 4, 6, 8],
    tuitionMin: 2500,
    tuitionMax: 9500,
    size: 500,
    founded: 1958,
    interests: ["waterfront", "team-sports", "arts-theater", "nature-animals", "stem"],
    vibe: 3,
    competitiveness: 1,
    structure: 3,
    religious: "none",
    supports: ["food-allergies", "inclusion-program"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A third-generation family-run Rockland County day camp — heated pools, warm culture and flexible 2–8 week enrollment, minutes from the NJ border.",
    website: "https://www.deerkilldaycamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "gate-hill-day-camp",
    name: "Gate Hill Day Camp",
    type: "day",
    city: "Stony Point",
    state: "NY",
    region: "northeast",
    lat: 41.23,
    lng: -74.03,
    ageMin: 3,
    ageMax: 15,
    gender: "coed",
    sessionWeeks: [4, 6, 8],
    tuitionMin: 4000,
    tuitionMax: 9800,
    size: 700,
    founded: 1969,
    interests: ["waterfront", "team-sports", "action-sports", "arts-theater", "outdoor-adventure"],
    vibe: 4,
    competitiveness: 2,
    structure: 3,
    religious: "none",
    supports: ["food-allergies"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "A Rockland County day camp on 100 wooded acres — lake and pool aquatics, adventure elements and busing throughout the NY/NJ border towns.",
    website: "https://www.gatehillcamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "galileo-camps",
    name: "Camp Galileo",
    type: "day",
    city: "Palo Alto",
    state: "CA",
    region: "west",
    lat: 37.44,
    lng: -122.14,
    ageMin: 5,
    ageMax: 14,
    gender: "coed",
    sessionWeeks: [1, 2, 4, 8],
    tuitionMin: 500,
    tuitionMax: 6000,
    size: 300,
    founded: 2002,
    interests: ["stem", "arts-theater", "outdoor-adventure"],
    vibe: 5,
    competitiveness: 1,
    structure: 3,
    religious: "none",
    supports: ["food-allergies", "inclusion-program"],
    firstTimeFriendly: true,
    acaAccredited: false,
    description:
      "An innovation-themed day camp at dozens of West Coast and Chicagoland sites — design thinking, making and art in weekly flexible blocks.",
    website: "https://www.galileo-camps.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "steve-and-kates-camp",
    name: "Steve & Kate's Camp",
    type: "day",
    city: "Brooklyn",
    state: "NY",
    region: "northeast",
    lat: 40.69,
    lng: -73.98,
    ageMin: 4,
    ageMax: 12,
    gender: "coed",
    sessionWeeks: [1, 2, 4, 8],
    tuitionMin: 120,
    tuitionMax: 6500,
    size: 300,
    founded: 1980,
    interests: ["stem", "arts-theater", "music", "gymnastics-dance"],
    vibe: 5,
    competitiveness: 1,
    structure: 5,
    religious: "none",
    supports: ["food-allergies", "inclusion-program"],
    firstTimeFriendly: true,
    acaAccredited: false,
    description:
      "Day-pass-based day camps in cities nationwide where kids choose everything — bread-making, sewing, coding, media lab — with any-day flexibility and refunds for unused days.",
    website: "https://www.steveandkatescamp.com",
    claimed: false,
    verified: false,
  },
  {
    slug: "oasis-day-camp-central-park",
    name: "Oasis Day Camp in Central Park",
    type: "day",
    city: "New York",
    state: "NY",
    region: "northeast",
    lat: 40.79,
    lng: -73.96,
    ageMin: 5,
    ageMax: 14,
    gender: "coed",
    sessionWeeks: [2, 4, 6, 8],
    tuitionMin: 1500,
    tuitionMax: 7000,
    size: 400,
    founded: 1998,
    interests: ["team-sports", "arts-theater", "stem", "outdoor-adventure"],
    vibe: 3,
    competitiveness: 1,
    structure: 3,
    religious: "none",
    supports: ["food-allergies", "inclusion-program"],
    firstTimeFriendly: true,
    acaAccredited: true,
    description:
      "An urban day camp using Central Park as its backyard — sports, swim and arts for city kids with flexible sessions.",
    website: "https://www.oasischildren.com",
    claimed: false,
    verified: false,
  },
];
